export type Language = 'zh' | 'en';

export const COPY = {
  zh: {
    navLabel: '頁面導覽', navAnchor: '建立存證', navVerify: '驗證檔案', navHistory: '公開紀錄',
    languageLabel: '語言', contractLive: '合約已啟用', contractPending: '等待部署',
    connectWallet: '連接測試錢包', testEth: '測試 ETH',
    eyebrow: '私人研究紀錄，公開時間證明', headline: '替研究留下可信的時間線索。',
    lead: '原始檔留在你的裝置。網站只計算檔案指紋，再把指紋與時間寫進 Base 測試鏈。',
    privacyTitle: '原始檔不上傳', privacyBody: '照片、影片與數據不會送到伺服器或 IPFS。',
    startAnchor: '開始建立存證', startVerify: '直接驗證檔案', walletNeeded: '建立時需要錢包',
    flowLabel: '運作方式', flowLocalTitle: '本機建立指紋', flowLocalBody: '瀏覽器計算 SHA-256',
    flowBaseTitle: 'Base 留下時間', flowBaseBody: '只保存指紋、標題與短備註',
    flowVerifyTitle: '任何人都能驗證', flowVerifyBody: '查驗不需要連接錢包',
    workspaceLabel: '研究存證工具', stepOne: '第一步', anchorTitle: '替研究留下證明',
    anchorHelp: '支援照片、影片、CSV、PDF 與其他檔案。內容只在這台裝置內讀取。',
    anchorDrop: '拖入研究檔案', chooseFile: '或點這裡選擇檔案', titleLabel: '研究名稱',
    titlePlaceholder: '例如：電池電解液實驗，第 3 天', hashLabel: '本機檔案指紋（SHA-256）',
    noteLabel: '公開文字（可留白）', notePlaceholder: '自由輸入想公開記下的短文字',
    noteHint: '可自由輸入；這段文字會永久公開寫入 Base，請勿填敏感資料。',
    hashEmpty: '選擇檔案後，這裡會出現指紋', anchorAction: '在 Base 留下證明',
    copyHash: '複製檔案指紋',
    stepTwo: '第二步', verifyTitle: '驗證原始檔',
    verifyHelp: '選擇要查驗的檔案。指紋相同，代表檔案內容沒有改變。',
    verifyDrop: '拖入要驗證的檔案', noWallet: '不用連接錢包', creator: '建立者',
    time: '時間', explorer: '查看 Base 紀錄', passportEyebrow: '研究誠信護照',
    passportTitle: '公開研究紀錄', passportEmpty: '連接錢包，或輸入公開錢包地址後，這裡會顯示存證時間軸。',
    timelineHelp: '不用錢包也能輸入公開地址，查看任何人的公開存證紀錄。',
    timelineLabel: '公開錢包地址', timelinePlaceholder: '貼上 0x 開頭的公開錢包地址', timelineLookupAction: '查看紀錄',
    scoreLabel: '持續記錄分數',
    scoreNote: '依存證筆數、不同記錄日與持續時間計算；它不代表研究內容一定正確。',
    refresh: '更新我的紀錄', refreshing: '讀取中...',
    noRecords: '還沒有紀錄。完成第一筆存證後，它會出現在這裡。',
    evidenceEyebrow: '可檢查的技術證據', evidenceTitle: '不是示意圖，是真的測試網紀錄。',
    evidenceBody: '合約原始碼已驗證；Chainlink 機密流程已用合成資料完成本機模擬。',
    contractEvidence: 'Base Sepolia 智能合約', contractEvidenceDetail: '公開查看程式碼與鏈上紀錄',
    creEvidence: 'Chainlink CRE', simulationPassed: '機密流程模擬成功',
    creEvidenceDetail: 'TEE handler 只輸出 commitment', copyCommitment: '複製模擬 commitment',
    simulationOnly: 'Chainlink 部分目前是成功的本機模擬，尚未部署成線上 workflow。',
    faqEyebrow: '簡單說明', faqTitle: '你不需要先懂區塊鏈。',
    faq: [
      ['連接錢包是做什麼？', '錢包像你的數位簽名。只有建立存證時才需要確認；查驗檔案不需要錢包。'],
      ['沒有錢包或沒有測試 ETH，還能使用嗎？', '可以驗證檔案，也能輸入公開地址查看紀錄。只有建立新的鏈上存證時，才需要錢包與 Base Sepolia 測試 ETH。'],
      ['合約地址是什麼？', '它是網站讀寫 Base 帳本的位置。部署前網站會顯示「等待部署」，不會假裝資料已經上鏈。'],
      ['這能證明我是作者嗎？', '它能證明某個檔案指紋在某個鏈上時間已存在，不能單獨決定著作權、專利權或研究品質。'],
      ['分數代表研究一定是真的嗎？', '不代表。分數只整理公開存證的次數與持續時間，不能取代同行評審、實驗重現或法律判斷。'],
    ],
    footer: 'DeSci Proof Notebook · Base Sepolia 測試網 · v0.5.4',
    messages: {
      walletMissing: '找不到錢包。請先安裝並開啟 MetaMask。',
      networkAddFailed: '無法加入 Base Sepolia，請在錢包中確認後再試。',
      walletCancelled: '你取消了錢包連接，或錢包暫時無法使用。',
      hashing: '正在你的裝置內計算指紋，檔案不會被上傳。',
      hashReady: '指紋已完成。接著替這份研究取一個名稱。',
      fileUnreadable: '這個檔案無法讀取，請換一個檔案再試。', fileRequired: '請先選擇一個檔案。',
      titleRequired: '請替這份研究填一個簡短名稱。', titleLong: '研究名稱太長，請縮短一點再試。',
      noteLong: '公開文字太長，請縮短到 280 bytes 內。',
      walletRequired: '請先連接 Base Sepolia 測試錢包。',
      contractPending: '合約還沒有部署。部署完成後，這個按鈕才會送出測試交易。',
      confirmWallet: '請在錢包確認這筆 Base Sepolia 測試交易。',
      transactionSent: '交易已送出，正在等待 Base Sepolia 記錄。',
      anchorSuccess: '存證完成。原始檔案從頭到尾都沒有離開你的裝置。',
      transactionCancelled: '你取消了錢包交易。',
      transactionFailed: '存證沒有完成，請確認錢包網路與測試 ETH 後再試。',
      verifying: '正在本機計算並比對檔案指紋。',
      verifyPending: '驗證合約還沒部署，因此目前無法查詢鏈上紀錄。',
      noProof: '找不到這份檔案的存證。它可能未曾存證，或內容曾被修改。',
      verifySuccess: '驗證通過。這份檔案的指紋與 Base 上的紀錄完全相同。',
      verifyFailed: '無法完成驗證，請檢查網路後再試。',
      timelineAddressInvalid: '請輸入有效的 0x 開頭公開錢包地址。',
      timelineReadFailed: '無法讀取公開紀錄，請檢查網路後再試。',
    },
  },
  en: {
    navLabel: 'Page navigation', navAnchor: 'Create proof', navVerify: 'Verify file', navHistory: 'Public history',
    languageLabel: 'Language', contractLive: 'Contract live', contractPending: 'Awaiting deployment',
    connectWallet: 'Connect test wallet', testEth: 'test ETH', eyebrow: 'Private research, public timestamp',
    headline: 'Give your research a verifiable point in time.',
    lead: 'Your original file stays on your device. The app calculates a fingerprint and records only that fingerprint and time on Base testnet.',
    privacyTitle: 'Original file never uploads', privacyBody: 'Photos, videos, and data are not sent to a server or IPFS.',
    startAnchor: 'Create a proof', startVerify: 'Verify a file now', walletNeeded: 'Wallet needed to create',
    flowLabel: 'How it works', flowLocalTitle: 'Fingerprint locally', flowLocalBody: 'SHA-256 runs in your browser',
    flowBaseTitle: 'Timestamp on Base', flowBaseBody: 'Hash, title, and a short note are stored',
    flowVerifyTitle: 'Verify from anywhere', flowVerifyBody: 'Checking does not need a wallet',
    workspaceLabel: 'Research proof workspace', stepOne: 'Step one', anchorTitle: 'Create a research proof',
    anchorHelp: 'Works with photos, videos, CSV, PDF, and other files. Content is read only on this device.',
    anchorDrop: 'Drop a research file', chooseFile: 'or click here to choose a file', titleLabel: 'Research title',
    titlePlaceholder: 'Example: Battery electrolyte test, day 3', hashLabel: 'Local file fingerprint (SHA-256)',
    noteLabel: 'Public text (optional)', notePlaceholder: 'Write any short text you want to make public',
    noteHint: 'You may write freely. This text is permanently public on Base; do not include sensitive information.',
    hashEmpty: 'Choose a file to calculate its fingerprint', anchorAction: 'Create proof on Base',
    copyHash: 'Copy file fingerprint',
    stepTwo: 'Step two', verifyTitle: 'Verify an original file',
    verifyHelp: 'Choose a file to check. A matching fingerprint means its contents have not changed.',
    verifyDrop: 'Drop a file to verify', noWallet: 'No wallet required', creator: 'Creator', time: 'Time',
    explorer: 'View Base record', passportEyebrow: 'Research integrity passport', passportTitle: 'Your public history',
    passportEmpty: 'Connect a wallet or enter a public wallet address to view a proof timeline.',
    timelineHelp: 'No wallet is needed. Enter any public wallet address to view its proof history.',
    timelineLabel: 'Public wallet address', timelinePlaceholder: 'Paste a public wallet address starting with 0x', timelineLookupAction: 'View history',
    scoreLabel: 'Continuity score',
    scoreNote: 'Calculated from proof count, distinct recording days, and time span. It does not mean the research is correct.',
    refresh: 'Refresh my records', refreshing: 'Loading...',
    noRecords: 'No records yet. Your first completed proof will appear here.',
    evidenceEyebrow: 'Verifiable technical evidence', evidenceTitle: 'A working testnet record, not a mockup.',
    evidenceBody: 'The contract source is verified, and the Chainlink confidential workflow has passed a local simulation with synthetic data.',
    contractEvidence: 'Base Sepolia smart contract', contractEvidenceDetail: 'Inspect the source and onchain records',
    creEvidence: 'Chainlink CRE', simulationPassed: 'Confidential simulation passed',
    creEvidenceDetail: 'The TEE handler outputs only a commitment', copyCommitment: 'Copy simulation commitment',
    simulationOnly: 'The Chainlink component is a successful local simulation and is not yet deployed as a live workflow.',
    faqEyebrow: 'Plain-language answers', faqTitle: 'No blockchain experience required.',
    faq: [
      ['What does connecting a wallet do?', 'A wallet works like your digital signature. It is needed only to create a proof; file verification does not require one.'],
      ['Can I use it without a wallet or test ETH?', 'Yes, for file verification and public-history lookup. A wallet and Base Sepolia test ETH are needed only to create a new onchain proof.'],
      ['What is the contract address?', 'It is the location this site reads and writes on Base. Before deployment, the site says “Awaiting deployment” and never pretends data is onchain.'],
      ['Does this prove I am the author?', 'It proves that a file fingerprint existed at an onchain time. It cannot decide copyright, patent rights, or research quality by itself.'],
      ['Does the score mean the research is true?', 'No. It only summarizes public proof activity over time. It cannot replace peer review, replication, or legal judgment.'],
    ],
    footer: 'DeSci Proof Notebook · Base Sepolia testnet · v0.5.4',
    messages: {
      walletMissing: 'No wallet was found. Install and open MetaMask first.',
      networkAddFailed: 'Base Sepolia could not be added. Confirm the request in your wallet and try again.',
      walletCancelled: 'You cancelled the connection, or the wallet is temporarily unavailable.',
      hashing: 'Calculating the fingerprint on your device. The file is not uploaded.',
      hashReady: 'Fingerprint ready. Give this research file a short title.',
      fileUnreadable: 'This file could not be read. Please try another file.', fileRequired: 'Choose a file first.',
      titleRequired: 'Add a short research title.', titleLong: 'The research title is too long. Please shorten it.',
      noteLong: 'The public text is too long. Keep it within 280 bytes.',
      walletRequired: 'Connect a Base Sepolia test wallet first.',
      contractPending: 'The contract is not deployed yet. This button will send a test transaction after deployment.',
      confirmWallet: 'Confirm this Base Sepolia test transaction in your wallet.',
      transactionSent: 'Transaction sent. Waiting for Base Sepolia to record it.',
      anchorSuccess: 'Proof complete. The original file never left your device.',
      transactionCancelled: 'You cancelled the wallet transaction.',
      transactionFailed: 'The proof was not completed. Check the wallet network and test ETH, then try again.',
      verifying: 'Calculating and checking the file fingerprint locally.',
      verifyPending: 'The verification contract has not been deployed, so onchain records are not available yet.',
      noProof: 'No proof was found. The file may be unregistered or its contents may have changed.',
      verifySuccess: 'Verified. This file fingerprint exactly matches the record on Base.',
      verifyFailed: 'Verification could not be completed. Check your connection and try again.',
      timelineAddressInvalid: 'Enter a valid public wallet address starting with 0x.',
      timelineReadFailed: 'Public history could not be read. Check your connection and try again.',
    },
  },
} as const;
